GET http://localhost:8080/api/tasks

###

GET http://localhost:8080/api/tasks/6198e7bb0ccd01d26c6ddab4

###

POST http://localhost:8080/api/task

{
  "title": "Task 3",
  "description": "Task 3 description",
#   "done": false,
#   "createdBy": "Daiver"
}